<a href="https://colab.research.google.com/github/Kadergueli/conflict-risk-analysis-chad/blob/main/02_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/ACLED_CHAD_RESEARCH/data/acled_chad.csv')
#vue des données existants
df.shape
df.columns
print(df.head())

   GWNO EVENT_ID_CNTY  EVENT_ID_NO_CNTY  EVENT_DATE  YEAR  TIME_PRECISION  \
0   483          3CHA             12256  15/02/1997  1997               3
1   483          1CHA             12254  15/02/1997  1997               3
2   483          2CHA             12255  15/02/1997  1997               3
3   483          4CHA             12257  15/07/1997  1997               3
4   483          5CHA             12258  24/07/1997  1997               2

                      EVENT_TYPE                                     ACTOR1  \
0     Violence against civilians                           Civilians (Chad)
1     Violence against civilians  FARF: Armed Forces for a Federal Republic
2     Violence against civilians  FARF: Armed Forces for a Federal Republic
3  Battle-No change of territory          FDR: Democratic Front for Renewal
4     Violence against civilians            Unidentified Armed Group (Chad)

                  ALLY_ACTOR_1  INTER1  ...           ADMIN1     ADMIN2  \
0  Chadian Human Rights League       7  ...  Logone Oriental  Nya Pendé
1                          NaN       2  ...  Logone Oriental  Nya Pendé
2                          NaN       2  ...  Logone Oriental      Lanya
3                          NaN       2  ...            Guéra      Guéra
4                          NaN       3  ...      Moyen-Chari    Lac Iro

       ADMIN3    LOCATION  LATITUDE LONGITUDE GEO_PRECIS  \
0    Mbaikoro     Moundou   8,56670  16,08330          1
1  Kaba-Donia       Donia   8,40509  16,42309          1
2      Mbikou      Mbikou   8,60141  16,39258          1
3    Mousmare        Bose  11,07000  17,83000          2
4  Boum-Kebir  Boum-Kabir  10,18000  19,39000          1

                     SOURCE  \
0     Amnesty International
1     Amnesty International
2     Amnesty International
3  Africa Research Bulletin
4                   Reuters

                                               NOTES FATALITIES
0  Firmin Nengomnang, an LTDH member, was assault...          0
1                               FARF kills civilians          1
2                               FARF kills civilians          2
3  Battle from 10/19-10/20. Fatalities: 40 soldie...         40
4  looted officials home; attacked and wounded tw...          0

[5 rows x 25 columns]

In [17]:
#elimination des cellules non indispensables
df.info()
df = df.drop(columns=['GWNO','EVENT_ID_CNTY','EVENT_ID_NO_CNTY','SOURCE','NOTES','ALLY_ACTOR_1','ACTOR1','ACTOR2','INTER1','INTER2','ALLY_ACTOR_2'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GWNO              558 non-null    int64
 1   EVENT_ID_CNTY     558 non-null    object
 2   EVENT_ID_NO_CNTY  558 non-null    int64
 3   EVENT_DATE        558 non-null    object
 4   YEAR              558 non-null    int64
 5   TIME_PRECISION    558 non-null    int64
 6   EVENT_TYPE        558 non-null    object
 7   ACTOR1            558 non-null    object
 8   ALLY_ACTOR_1      45 non-null     object
 9   INTER1            558 non-null    int64
 10  ACTOR2            522 non-null    object
 11  ALLY_ACTOR_2      44 non-null     object
 12  INTER2            558 non-null    int64
 13  INTERACTION       558 non-null    int64
 14  COUNTRY           558 non-null    object
 15  ADMIN1            558 non-null    object
 16  ADMIN2            558 non-null    object
 17  ADMIN3            558 non-null    object
 18  LOCATION          558 non-null    object
 19  LATITUDE          558 non-null    object
 20  LONGITUDE         558 non-null    object
 21  GEO_PRECIS        558 non-null    int64
 22  SOURCE            558 non-null    object
 23  NOTES             499 non-null    object
 24  FATALITIES        558 non-null    int64
dtypes: int64(9), object(16)
memory usage: 109.1+ KB

In [18]:
# nouvelle forme du dataframe
df.shape
df.head()

,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,INTERACTION,COUNTRY,ADMIN1,ADMIN2,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECIS,FATALITIES
0,15/02/1997,1997,3,Violence against civilians,17,Chad,Logone Oriental,Nya Pendé,Mbaikoro,Moundou,"8,56670","16,08330",1,0
1,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Nya Pendé,Kaba-Donia,Donia,"8,40509","16,42309",1,1
2,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Lanya,Mbikou,Mbikou,"8,60141","16,39258",1,2
3,15/07/1997,1997,3,Battle-No change of territory,12,Chad,Guéra,Guéra,Mousmare,Bose,"11,07000","17,83000",2,40
4,24/07/1997,1997,2,Violence against civilians,37,Chad,Moyen-Chari,Lac Iro,Boum-Kebir,Boum-Kabir,"10,18000","19,39000",1,0

In [20]:
#calcul statistique pour verifier les valeurs marquantes
df.describe()
df.isnull().sum()

EVENT_DATE        0
YEAR              0
TIME_PRECISION    0
EVENT_TYPE        0
INTERACTION       0
COUNTRY           0
ADMIN1            0
ADMIN2            0
ADMIN3            0
LOCATION          0
LATITUDE          0
LONGITUDE         0
GEO_PRECIS        0
FATALITIES        0
dtype: int64

In [21]:
# elimination des doublons
df.drop_duplicates()

,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,INTERACTION,COUNTRY,ADMIN1,ADMIN2,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECIS,FATALITIES
0,15/02/1997,1997,3,Violence against civilians,17,Chad,Logone Oriental,Nya Pendé,Mbaikoro,Moundou,"8,56670","16,08330",1,0
1,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Nya Pendé,Kaba-Donia,Donia,"8,40509","16,42309",1,1
2,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Lanya,Mbikou,Mbikou,"8,60141","16,39258",1,2
3,15/07/1997,1997,3,Battle-No change of territory,12,Chad,Guéra,Guéra,Mousmare,Bose,"11,07000","17,83000",2,40
4,24/07/1997,1997,2,Violence against civilians,37,Chad,Moyen-Chari,Lac Iro,Boum-Kebir,Boum-Kabir,"10,18000","19,39000",1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,11/11/2014,2014,1,Violence against civilians,16,Chad,Moyen-Chari,Barh K÷h,Sarh,Sarh,"9,14980","18,38000",1,0
554,11/11/2014,2014,1,Riots/Protests,15,Chad,Logone Occidental,Lac Wey,Mballa,Moundou,"8,69960","16,06790",1,0
555,11/11/2014,2014,1,Riots/Protests,15,Chad,Ville de N'Djamena,N'Djamena,Ndjamena,N'Djamena,"12,10850","15,04820",1,0
556,28/11/2014,2014,1,Riots/Protests,60,Chad,Ville de N'Djamena,N'Djamena,Ndjamena,N'Djamena,"12,10850","15,04820",1,0
557,01/12/2014,2014,1,Riots/Protests,60,Chad,Ville de N'Djamena,N'Djamena,Ndjamena,N'Djamena,"12,10850","15,04820",1,0

In [23]:
# nouvelle dimension du dataframe
df.shape
df.head()

,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,INTERACTION,COUNTRY,ADMIN1,ADMIN2,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECIS,FATALITIES
0,15/02/1997,1997,3,Violence against civilians,17,Chad,Logone Oriental,Nya Pendé,Mbaikoro,Moundou,"8,56670","16,08330",1,0
1,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Nya Pendé,Kaba-Donia,Donia,"8,40509","16,42309",1,1
2,15/02/1997,1997,3,Violence against civilians,27,Chad,Logone Oriental,Lanya,Mbikou,Mbikou,"8,60141","16,39258",1,2
3,15/07/1997,1997,3,Battle-No change of territory,12,Chad,Guéra,Guéra,Mousmare,Bose,"11,07000","17,83000",2,40
4,24/07/1997,1997,2,Violence against civilians,37,Chad,Moyen-Chari,Lac Iro,Boum-Kebir,Boum-Kabir,"10,18000","19,39000",1,0

In [27]:
df['FATALITIES'] = df['FATALITIES'].fillna(0)

In [32]:
#regroupement par regions
df.groupby('ADMIN1').count()

,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,INTERACTION,COUNTRY,ADMIN2,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECIS,FATALITIES
ADMIN1,,,,,,,,,,,,,
Batha,5,5,5,5,5,5,5,5,5,5,5,5,5
Bet,80,80,80,80,80,80,80,80,80,80,80,80,80
Chari-Baguirmi,3,3,3,3,3,3,3,3,3,3,3,3,3
Guéra,11,11,11,11,11,11,11,11,11,11,11,11,11
Hadjer-Lamis,4,4,4,4,4,4,4,4,4,4,4,4,4
Kanem,12,12,12,12,12,12,12,12,12,12,12,12,12
Lac,3,3,3,3,3,3,3,3,3,3,3,3,3
Logone Occidental,5,5,5,5,5,5,5,5,5,5,5,5,5
Logone Oriental,17,17,17,17,17,17,17,17,17,17,17,17,17
Mandoul,4,4,4,4,4,4,4,4,4,4,4,4,4
Mayo-Kebbi Est,6,6,6,6,6,6,6,6,6,6,6,6,6
Mayo-Kebbi Ouest,4,4,4,4,4,4,4,4,4,4,4,4,4
Moyen-Chari,11,11,11,11,11,11,11,11,11,11,11,11,11
Ouaddaï,210,210,210,210,210,210,210,210,210,210,210,210,210
Salamat,15,15,15,15,15,15,15,15,15,15,15,15,15
Ville de N'Djamena,109,109,109,109,109,109,109,109,109,109,109,109,109
Wadi Fira,59,59,59,59,59,59,59,59,59,59,59,59,59

In [28]:
#verification final
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558 entries, 0 to 557
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EVENT_DATE      558 non-null    datetime64[ns]
 1   YEAR            558 non-null    int64
 2   TIME_PRECISION  558 non-null    int64
 3   EVENT_TYPE      558 non-null    object
 4   INTERACTION     558 non-null    int64
 5   COUNTRY         558 non-null    object
 6   ADMIN1          558 non-null    object
 7   ADMIN2          558 non-null    object
 8   ADMIN3          558 non-null    object
 9   LOCATION        558 non-null    object
 10  LATITUDE        558 non-null    object
 11  LONGITUDE       558 non-null    object
 12  GEO_PRECIS      558 non-null    int64
 13  FATALITIES      558 non-null    int64
dtypes: datetime64[ns](1), int64(5), object(8)
memory usage: 61.2+ KB

In [30]:
#save
df.to_csv('/content/drive/MyDrive/ACLED_CHAD_RESEARCH/data/cleaned_acled_chad.csv', index=False)

## Cleaning Summary

- Removed duplicates
- Converted dates
- Filled missing fatalities
- Dataset ready for analysis